author: Tuist
module: XcodeProj
github_url: https://github.com/tuist/xcodeproj
copyright: 'Copyright © from 2018 Pedro Piñera Buendía. All rights reserved.'
readme: ABOUT.md
documentation: guides/*.md
sdk: macosx
xcodebuild_arguments:
  - -project
  - XcodeProj.xcodeproj
  - -scheme
  - XcodeProj-Package
skip_undocumented: true
custom_categories:
  - name: Models
    children:
      - BuildSettings
      - XCConfig
      - XCWorkspace
      - XcodeProj
      - XCBuildConfiguration
      - XCConfigurationList
      - XCScheme
      - XCSharedData
      - PBXProductType
      - PBXNativeTarget
      - PBXProj
      - PBXObject
      - PBXSourceTree
      - PBXAggregateTarget
      - PBXBuildFile
      - PBXContainerItemProxy
      - PBXFileElement
      - PBXFileReference
      - PBXGroup
      - PBXProject
      - PBXFrameworksBuildPhase
      - PBXHeadersBuildPhase
      - PBXResourcesBuildPhase
      - PBXCopyFilesBuildPhase
      - PBXShellScriptBuildPhase
      - PBXSourcesBuildPhase
      - PBXTargetDependency
      - PBXVariantGroup
  - name: Protocols
    children:
      - ProjectElement
  - name: Errors
    children:
      - XCConfigError
      - XCSchemeError
      - XCSharedDataError
      - XCWorkspaceDataError
      - XCWorkspaceError
      - XCodeProjError
      - PBXObjectError
